from typing import Protocol, runtime_checkable
from src.models import Lead, LeadStatus


@runtime_checkable
class LeadRepository(Protocol):
    def save_lead(self, lead: Lead) -> None: ...
    def get_lead(self, domain: str) -> Lead | None: ...
    def list_by_status(self, status: LeadStatus, limit: int = 50) -> list[Lead]: ...
    def update_status(self, domain: str, status: LeadStatus) -> None: ...
